### ISSUE TITLE
S9992 error for one web application but not for 2nd web application and 2 unit test projects

### ISSUE THREAD

**Issue by BlackMael** [eWAYPayment/eway-rapid-net#24]
I have posted this question to stackoverflow... https://stackoverflow.com/questions/44520289/eway-rapid-error-s9992-keeps-occuring-on-asp-net-mvc-application

```
var ewayClient = RapidClientFactory.NewRapidClient(Platform.eWayApiKey, Platform.eWayPassword, EndPoint);
ewayClient.SetVersion(31);

var transaction = CreateTransaction();
var preAuthTransaction = ewayClient.Create(PaymentMethod.ResponsiveShared, transaction);

Assert.IsNull(preAuthTransaction.Errors);
```

It sets up a basic transaction but it is failing in 1 out of 4 contexts.

I have two solutions each with a web application and a unit test project.  They all return a response with no Errors except for one of the web applications which returns that S9992 error code.

The web applications are running under IIS Express 10.  The app that fails locally on IIS Express also fails when deployed to external web site.

I am pulling my hair out over this.

NOTE: I'm using  NuGet package version 1.6.0-beta1

**Comment by incarnate** [comment]
Hi @BlackMael 

Thanks for raising this, have you spoken to the eWAY customer support team? They are the best people to ask with any issues you have with the SDKs.

As I'm sure you are aware, S9992 is a communications error. Most of these are caused by either your system not having up-to-date root certificates or .NET not being able to connect over TLS 1.2. 

If you haven't already, are you able to debug and step through from a break point in your local IIS instance to get the exact error?

**Comment by BlackMael** [comment]
Hi @incarnate 

I finally found the solution.

I had to set the SecurityProtocol

```
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12
```

I felt my issue was more .NET related and apparently my Google-fu was lacking.

I know eWay were changing to require TLS 1.2 (see https://myeway.force.com/success/s/article/ka828000000L2mlAAC/I-am-testing-in-Sandbox-and-I-am-receiving-an-error-that-the-connection-has-been-closed)

But reason that one .NET web app running on my development machine needed me to add that line, when another .NET web application and two unit test projects across two separate solutions didn't still alludes me.
Everything is running .NET 4.6+
It seems 4.0 and 4.5 don't support TLS 1.2 by default and that 4.6+ does. My one app that is failing is starting up set to Ssl3.  But it is .NET 4.6.1 so I'm confused.

Anyhoo... I just thought I'd mention my findings here as it may help someone else in the future.

**Comment by incarnate** [comment]
Thanks for following up with your fix @BlackMael 

It is certainly strange that you're seeing the issue while running .NET 4.6 since it should default to TLS 1.2 as you say. The stable release of the eWAY .NET SDK has got management of the TLS settings built in since v1.5.1, but that fix isn't in the beta yet.

Hope the rest of your project goes smoothly!
