### ISSUE TITLE
Look up meaning of response codes programmatically

### ISSUE THREAD

**Issue by ianleeder** [eWAYPayment/eway-rapid-net#6]
Got a feature request to lodge, the API shows all these lovely [response messages](https://eway.io/api-v3/?csharp#transaction-response-messages), but all I receive is a string code (e.g. "D4433").  It would be nice if the SDK provided a way to translate that into meaningful strings (to provide to customer explaining why transaction was declined, e.g. "Expired Card, Capture").

I figure you could either make it as a `readonly Dictionary`, or you could make a `GetMessageFromResponseCode` helper method (similar to `RapidClientFactory.UserDisplayMessage`).

**Comment by incarnate** [comment]
Hi Ian,

You are in luck, this is a feature already available in the SDK, you'll see it used in many of the response handling examples in the Rapid API Reference:

```
RapidClientFactory.UserDisplayMessage(errorCode, "EN")
```

That said, we typically recommend against displaying the error messages to customers and just logging them to your backend system. This is both for security (you don't want a fraudster to know they were flagged for fraud for example) and because the banks use of response codes isn't very consistent, which could confuse customers. Validation messages (such as invalid card number) aren't generally a problem, although you can usually protect against them with some client side validation.

Hope that helps!

**Comment by ianleeder** [comment]
:facepalm:
Of course you are right.  That was stupid. I knew about that method, but didn't consider it would include all response codes.  I had used it in the context of [System Response Codes](https://eway.io/api-v3/?csharp#system-response-codes), but they are no different to [Transaction Response Messages](https://eway.io/api-v3/?csharp#transaction-response-messages).

Can you add the tag "stupid question"?

And with regards to showing them to end user, yes, I am still thinking about this.  Currently just duplicating an existing payment system that _did_ return them, but I'll speak to management about that.
